"""empty message

Revision ID: 443202e1eac2
Revises: 8dc6534f842c
Create Date: 2025-05-12 21:19:57.403740

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '443202e1eac2'
down_revision: Union[str, None] = '8dc6534f842c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'difficult_levels', ['name'])
    op.create_unique_constraint(None, 'questions', ['text'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_constraint(None, 'difficult_levels', type_='unique')
    # ### end Alembic commands ###
