"""empty message

Revision ID: a88cff0ee33b
Revises: 7df7e5f1fe5d
Create Date: 2025-05-13 13:28:00.062060

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a88cff0ee33b'
down_revision: Union[str, None] = '7df7e5f1fe5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_text_key', 'questions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('questions_text_key', 'questions', ['text'])
    # ### end Alembic commands ###
